### ISSUE TITLE
Agregar imagen del proyecto al archivo README

### ISSUE THREAD

**Issue by nicomartin8542** [FedeHerrera10/PoloTecno-Git#1]
Buenas noches Fede. Envió solicitud para agregar captura de pantalla del proyecto al archivo README para dejarlo mas completo. 

Aguardo comentarios. Saludos

**Comment by FedeHerrera10** [comment]
Buenas Nico muchas gracias por contribuir.

**Comment by FedeHerrera10** [comment]
Se agrego este screen. Gracias.
![2021-02-23-09-19-localhost](https://user-images.githubusercontent.com/26462775/108843004-df8e2880-75b8-11eb-9f38-c95c9d5a246c.png)
